[package]
name = "dump-syntax"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
colored = "3"
proc-macro2 = { package = "proc-macro2-send", git = "https://github.com/Riateche/proc-macro2.git", branch = "send", features = ["span-locations"] }

[dependencies.syn-send]
default-features = false
features = ["extra-traits", "full", "parsing"]
path = "../.."
